#!/usr/bin/env bash

# Nachprüfen, ob Virtualbox und Vagrant installiert sind

vagrant_command=$(vagrant --version)
vagrant_check=$?
virtualbox_command=$(vboxmanage --version)
virtualbox_check=$?

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

jboss="$DIR/Files/jb7_demo_Dump.sql"
liferay="$DIR/Files/jb7_liferay_Dump.sql"
jboss_dir="$DIR/Files/jboss"
liferay_dir="$DIR/Files/liferay"
java_sdk="$DIR/Files/jdk-7u79-linux-x64.rpm"
test_spec="$DIR/Files/test_spec.rb"

case "$1" in
  up)
  if [[ "$vagrant_check" -eq 0 ]]
  then
    echo -e "Erfolgreich \t\033[32;1mVagrant ist installiert\033[0m"
  else
    echo -e "Fehler \t\033[31;1mVagrant ist nicht installiert\033[0m"
    exit 1
  fi

  if [[ "$virtualbox_check" -eq 0 ]]
  then
    echo -e "Erfolgreich \t\033[32;1mVirtualBox ist installiert\033[0m"
  else
    echo -e "Fehler \t\033[31;1mVirtualBox ist nicht installiert\033[0m"
    exit 1
  fi
  if [[ -e "$jboss" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mJBoss Dump File gefunden\033[0m"
  else
    echo -e "Fehler \t\033[31;1mJBoss Dump File nicht gefunden\033[0m"
    exit 1
  fi
  if [[ -f "$liferay" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mLiferay Dump File gefunden\033[0m"
  else
    echo -e "Fehler \t\t\033[31;1mLiferay Dump File nicht gefunden\033[0m"
    exit 1
  fi
  if [[ -d "$jboss_dir" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mJBoss Ordner gefunden\033[0m"
  else
    echo -e "Fehler \t\t\033[31;1mJBoss Ordner nicht gefunden\033[0m"
    exit 1
  fi
  if [[ -d "$liferay_dir" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mLiferay Ordner gefunden\033[0m"
  else
    echo -e "Fehler \t\t\033[31;1mLiferay Ordner nicht gefunden\033[0m"
    exit 1
  fi
  if [[ -f "$java_sdk" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mJava SDK RPM gefunden\033[0m"
  else
    echo -e "Fehler \t\t\033[31;1mJava SDK RPM nicht gefunden\033[0m"
    exit 1
  fi
  if [[ -f "$test_spec" ]]
  then
    echo -e "Erfolgreich \t\033[32;1mInSpec Test gefunden\033[0m"
  else
    echo -e "Fehler \t\t\033[31;1mInSpec Test nicht gefunden\033[0m"
    exit 1
  fi

  vagrant up
  echo "Hier die Resultate von dem VM Start:"
  echo "------------------------------------"
  cat "$DIR/Files/test_result"
  rm "$DIR/Files/test_result"
    ;;
  down)
  echo "Vagrant VM wird beendet und gelöscht..."
  vagrant halt && vagrant destroy -f
    ;;
  status)
  vagrant status
    ;;
  *)
  echo "Keine Argument übergeben"
  echo "Entweder mit 'up' starten"
  echo "Oder mit 'down' beenden"
    ;;
esac
